imports:
    - javascript
    - php

filter:
    excluded_paths: [vendor/*, pub/js/vendor/*, src/Tests/*]

tools:
    external_code_coverage:
        timeout: 7200    # Timeout in seconds. 120 minutes
